development:
  cloud_name: dp6qqwrw3
  api_key: '211743513481742'
  api_secret: o6MdRs2Q3OalMjzGuk3-lcloj_4
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dp6qqwrw3
  api_key: '211743513481742'
  api_secret: o6MdRs2Q3OalMjzGuk3-lcloj_4
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dp6qqwrw3
  api_key: '211743513481742'
  api_secret: o6MdRs2Q3OalMjzGuk3-lcloj_4
  enhance_image_tag: true
  static_file_support: false
